<?php

namespace EcommerceBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{

    public function byCategorie($categorie)
    {
        $qb = $this->createQueryBuilder('p')
            ->where('p.categorie = :categorie')
            ->orderBy('p.id')
            ->setParameter('categorie', $categorie);

        return $qb->getQuery()->getResult();
    }
}
